### ISSUE TITLE
冒昧问一下，应该如何在linux在运行？

### ISSUE THREAD

**Issue by ShadowsSide** [chr233/XinjingdailyBot#1]
我的服务器是甲骨文的Arm机，ubuntu 20.04

尝试了 ./XinjingdailyBot 提示
root@ubuntu:~/tougao-bot# ./XinjingdailyBot
-bash: ./XinjingdailyBot: No such file or directory

使用sh XinjingdailyBot
XinjingdailyBot: 1: Syntax error: word unexpected (expecting ")")

查阅了一下 C# 程序可以使用 mono，安装后
root@ubuntu:~/tougao-bot# mono XinjingdailyBot
Cannot open assembly 'XinjingdailyBot': File does not contain a valid CIL image.

自行尝试了多种方式均无法启动，不是很了解这个语言。。所以希望作者 可以告知一下相关指令，谢谢！！！还是说暂时不支持Arm64呢？

**Comment by ShadowsSide** [comment]
自己找到原因了。。。。确实是因为不支持Arm64导致的，使用amd架构的机器运行 ./XinjingdailyBot 就正常了。
![image](https://user-images.githubusercontent.com/61958350/192134813-48e20fd6-37b0-48d1-9668-3a1320f31c9b.png)

**Comment by chr233** [comment]
打包后的版本自带.net环境，可以直接运行，不需要mono
