### ISSUE TITLE
请问是否可以自定义审核时的标签

### ISSUE THREAD

**Issue by C3604** [chr233/XinjingdailyBot#12]
请问这几个标签可以自定义吗？
![8b99b3746091260fd560ecd67ad977f](https://github.com/chr233/XinjingdailyBot/assets/20517972/3dc1b76d-849e-44fb-a4ba-85cc0e88f772)

**Comment by chr233** [comment]
![image](https://github.com/chr233/XinjingdailyBot/assets/13798576/3a389b3f-9a9d-48ab-b971-1617f19b3bf8)

手动修改数据库tag表即可

**Comment by C3604** [comment]
多谢
