### ISSUE TITLE
不能清空命令菜单栏,无论是在BotFather还是其它方法

### ISSUE THREAD

**Issue by zhong820290** [chr233/XinjingdailyBot#16]
使用命令 /command 设置菜单后,尝试好几个方法都无法清空命令菜单栏,我其它机器人手动在教父机器人中设置命令或清空命令,可以正常使用,这是代码问题还是服务器问题?

**Comment by chr233** [comment]
不清楚，可能TG没有这么快生效

**Comment by zhong820290** [comment]
那能否增加一个清空命令菜单的命令呢

**Comment by zhong820290** [comment]
那也不对吧,我之前有一个测试的机器人,前几天我也尝试清空命令菜单栏,也是无法生效,这都好几天了

**Comment by zhong820290** [comment]
是不是代码有问题或者是增加一个取消命令菜单栏的命令

**Comment by zhong820290** [comment]
![image](https://github.com/chr233/XinjingdailyBot/assets/38713681/bb08fde2-adfe-4438-b5be-9f934b4505f8)
我在pyrogram库中,用获取机器人命令列表,也确实是空的,但是那命令栏还一直在,清不掉

**Comment by chr233** [comment]
![image](https://github.com/chr233/XinjingdailyBot/assets/13798576/58a63b4f-aa8c-4a40-b790-896bb804de95)

测试过了，是因为调用接口的时候指定了命令的scope范围，在botfather里设置的是默认scope的命令，需要修改`BotCommandScopeAllPrivateChats`等scope下的命令才可以完全删除命令菜单

**Comment by zhong820290** [comment]
非常棒,那我们就静候佳音吧
