### ISSUE TITLE
机器人的投稿能否自动解析来自 fxtwitter / vxtwitter / ddinstagram 等网站的链接预览？

### ISSUE THREAD

**Issue by HikariCalyx** [chr233/XinjingdailyBot#20]
目前，我们从每日无数猫频道 miaowu 收到的投稿如果来源是 fxtwitter / vxtwitter / ddinstagram / coolapk1s，在审核时还可以看到解析出来的图片和视频预览，但最终提交上去的只有一个链接，没有解析出预览图：
![image](https://github.com/chr233/XinjingdailyBot/assets/29157608/a40fd2a3-bb02-4949-aa92-04890e0dab04)
![image](https://github.com/chr233/XinjingdailyBot/assets/29157608/3bfe7ea3-f600-47b1-9ebc-4322ed174837)

另一边，通过WebpageBot就可以强行解析出链接预览。
![image](https://github.com/chr233/XinjingdailyBot/assets/29157608/b4607328-8b1f-4b79-9f4a-d54dd22675df)

想知道投稿机器人能否在投稿时，自动解析这类网站链接？

**Comment by chr233** [comment]
![image](https://github.com/chr233/XinjingdailyBot/assets/13798576/262d5b59-74d0-48e2-9fd1-1e8a95e8cb11)

是否启用链接预览由这个参数决定，当前设定为禁用预览

**Comment by chr233** [comment]
已加入，更新到 2.2.4.8 即可

**Comment by chr233** [comment]
配置位置如图

![image](https://github.com/chr233/XinjingdailyBot/assets/13798576/dc441b13-5904-4a3b-9040-0d73f359c6e1)

**Comment by HikariCalyx** [comment]
> 配置位置如图
> 
> ![image](https://private-user-images.githubusercontent.com/13798576/286794969-dc441b13-5904-4a3b-9040-0d73f359c6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTY4NDgsIm5iZiI6MTcwMTMxNjU0OCwicGF0aCI6Ii8xMzc5ODU3Ni8yODY3OTQ5NjktZGM0NDFiMTMtNTkwNC00YTNiLTkwNDAtMGQ3M2YzNTljNmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAzNTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OGYwMjNiYjg2ZWYyYjlmNGFjYmUzNWIzYTA3NGQzZGEwNGE2MmU1ZTE2MzE0MWM4Y2RkOGU1MzNhY2ExYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zr5Fyr8KQHcXljRVaGRe8VeVQb78zWldKH2RF_CC8H8)

昨天更新的时候有特意看了下 appsettings.json，现在可以正常使用了。
非常感谢。
![image](https://github.com/chr233/XinjingdailyBot/assets/29157608/535831d7-747d-4db3-a11a-521b8c114f7d)
