### ISSUE TITLE
用help命令 不定期出现 内部错误 提示

### ISSUE THREAD

**Issue by tsaoshuang** [chr233/XinjingdailyBot#21]
![image](https://github.com/chr233/XinjingdailyBot/assets/7597482/f32967e3-ff75-47f9-8609-555e491dd519)

**Comment by chr233** [comment]
这个命令应该坏了，有空修复

**Comment by Readfere** [comment]
> 这个命令应该坏了，有空修复，大概明年修

好的 辛苦了

**Comment by tsaoshuang** [comment]
> 这个命令应该坏了，有空修复，大概明年修

辛苦了

**Comment by chr233** [comment]
已修正
