### ISSUE TITLE
我应当如何启动它

### ISSUE THREAD

**Issue by sam13142023** [chr233/XinjingdailyBot#5]
怎么开始运行

**Comment by chr233** [comment]
解压以后运行 Xinjingdaily.WebAPI

**Comment by chr233** [comment]
[链接](https://btfy.eu.org/?q=5aaC5L2V6L+Q6KGMZXhl5paH5Lu2)

**Comment by samwang-fengniaozhineng** [comment]
你那也不是exe啊（（（

**Comment by chr233** [comment]
![image](https://user-images.githubusercontent.com/13798576/217011090-acf42a4f-b19b-47d9-9adc-fdc00991644d.png)

眼睛用不着可以捐给有需要的人

**Comment by sam13142023** [comment]
好的是我Linux不配

**Comment by sam13142023** [comment]
![image](https://user-images.githubusercontent.com/65808531/217013635-65c4d988-1fe3-4c34-b575-674638c0750b.png)
这里面有任何可执行文件吗？

**Comment by chr233** [comment]
Linux一样的，XinjingdailyBot.WebAPI就是启动文件, *.pdb是调试信息，可以删掉
